Fix/phone validation
eisbuk/EisBuk pull request #358
Opened 2022-02-10 13:20 UTC by ikusteu

Fixes #353 for `CustomerForm`. If needed, the new tickets for the rest of the validations should be opened, along with adding additional cypress tests for not-yet-tested functionality.

Additionally, some edge case tests for `CustomerForm` are there as well as some new util `cy` commands.

@silviot please add the italian translation for `ValidationMessages.InvalidPhone` message

2022-02-10 15:21 UTC, silviot requested changes

2022-02-10 16:39 UTC, ikusteu commented on eisbuk-admin/src/components/customers/CustomerForm/CustomerForm.tsx
> +    test: (input) => !input || /\+[0-9]*/.test(input),
Rightt…test just looks for a pattern…doesn’t enforce anything…thanks, I should update that in firestore.rules as well

2022-02-10 22:24 UTC, ikusteu commented
Fixed the requested functionlality and added test cases. I've also moved the whitespace removal to `CustomerForm`'s `onBlur` for given field (`phone`). I've also removed the commit adding whitespace manipulation to `updateCustomer` (as it is not needed anymore)

2022-02-11 09:35 UTC, silviot commented on eisbuk-admin/cypress/integration/athlete_form_spec.ts
> +  it.only("doesn't allow invalid phone input format", () => {
I guess `only` was left by mistake.

2022-02-13 22:53 UTC, silviot approved these changes

2022-02-14 10:32 UTC, merged