Feature/date switcher
eisbuk/EisBuk pull request #406
Opened 2022-03-07 15:13 UTC by fadwamahmoud

Fixes #384 
- Calendar icon is clicked to show the date picker.
- On slots view only Mondays are clickable.

2022-03-08 15:28 UTC, ikusteu requested changes

2022-03-08 15:28 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/DateSwitcher.tsx
> +import Menu from "@mui/material/Menu";
Here you can import `MenuProps` (as a named import)...Mui luckily provides the props interface for each of their components right by the component file...like we do in each `<componentFolder>/index.ts`

2022-03-08 15:28 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/DateSwitcher.tsx
> +  handleClose: () => void;
Here you can simply extend the aforementioned `MenuProps`:
```typescript
interface Props extends MenuProps {
  jump: DateTimeUnit // good one btw ;)
  currentDate: DateTime
}
```

2022-03-08 15:28 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/DateSwitcher.tsx
> +  handleClose: () => void;
This way the `onClose`, `open` and `anchorEl` will be included in the props interface. About `onClose` / `handleClose`, it is a convention to use `handle<something>` (i.e. `handleClick`) when you're writing a handler within the component, while all handlers received as props should be `on<something>` (i.e. `onClick`)

Example:
```typescript
const Button = ({ onClick, children }) => <button {...{ onClick }} >{children}</button>

const ButtonBox = () => {
  const handleClick = () => {/* do something */}
  return <Button onClick={handleClick} >Click Me</Button> 
}
```

2022-03-08 15:28 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/__tests__/DateSwitcher.test.tsx
> +    });
No need for smoke test, after you've written the stuff down below...successful rendering is implied for all of the other tests

2022-03-08 15:28 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/DateSwitcher.tsx
> +    </>
The menu doesn't close on outside click (and can't be closed at all)

2022-03-08 15:31 UTC, ikusteu commented on eisbuk-admin/src/components/atoms/DateSwitcher/DateSwitcher.tsx
> +    </>
My bad it most definitely works

2022-03-11 11:47 UTC, silviot approved these changes
Nice! It's exactly how I imagined it should be. I think it improves usability quite a bit. Good job!

2022-03-14 22:13 UTC, ikusteu approved these changes

2022-03-14 22:13 UTC, merged