Rehaul/old customer form refresh
eisbuk/EisBuk pull request #659
Opened 2022-09-10 12:14 UTC by ikusteu

Includes #657  (so it should be merged after)

Polished up the old CustomerForm with the ui components (removing MUI) and applied some fixes/extensions to form elements in the ui package.

2022-09-12 08:09 UTC, silviot requested changes
Nice! Looks great, apart from a couple of needed fixes.
The last field (card number) is triggering browser autocomplete for credit cards. An `autocomplete="off"` could solve this.
More importantly, category labels all point to the first category, so if you click on any category label the first checkbox will get triggered.

2022-09-16 11:00 UTC, silviot commented
Athlete currently can't see their data: https://eisbuk--rehaul-admin-preferences-refresh-4be8l1uj.web.app/customer_area/c5a16cc6-26c2-4ed8-9749-1641ae418181

Also, logged in as admin I was not able to save this form: when I click "save" nothing happens.

2022-09-16 12:03 UTC, delasous approved these changes

2022-09-19 11:49 UTC, silviot approved these changes

2022-09-19 11:49 UTC, merged