Rehaul/admin preferences refresh
eisbuk/EisBuk pull request #660
Opened 2022-09-10 21:35 UTC by ikusteu

Includes #659 
Includes #657 
Applies the UI package components and Tailwind styles to the `admin_preferences` page, with some minor fix-ups along the way. This is done to accommodate the country codes dropdown component, but also as a refresher of the entire section (to remove the MUI once and for all)

2022-09-12 08:13 UTC, silviot commented on packages/client/src/pages/admin_preferences/index.tsx
> +    name: "dislpayName",
Typo

2022-09-12 08:13 UTC, silviot commented on packages/client/src/components/atoms/FormSection/FormSection.stories.tsx
> +    name: "dislpayName",
typo

2022-09-12 08:15 UTC, silviot requested changes
Looks great! (except for the typo)

As a side note, it' soooo painful to type in these textareas rendered by React. It's a show stopper. It's my personal main reason a switch to Svelte is required.

2022-09-16 02:12 UTC, fadwamahmoud approved these changes

2022-09-16 12:02 UTC, delasous approved these changes
LGTM

2022-09-19 12:07 UTC, silviot approved these changes

2022-09-19 12:07 UTC, merged