Implement email templates
eisbuk/EisBuk pull request #690
Opened 2022-12-02 14:43 UTC by fadwamahmoud

Fixes #681

2022-12-06 09:14 UTC, ikusteu requested changes
I've commented on the PR, even though, some of the stuff I've commented should be changed altogether. 
As primary source of tasks, please use the updated #681 
After solving those, check the PR review comments, to fix the rest (and as future reference)

2022-12-17 14:28 UTC, ikusteu requested changes

2022-12-17 14:28 UTC, ikusteu commented on packages/functions/src/sendEmail/https.ts
> +      const emailTemplate = await fetchOrganizationEmailTemplate(
Can we name this `getOrganizationTemplate` rather than `fetch` to conform to the naming we use so far.

2022-12-17 14:28 UTC, ikusteu commented on packages/client/src/store/actions/bookingOperations.ts
> +  ({ icsFile, email, secretKey, displayName = "displayName", name = "name" }) =>
`displayName` should most definitely not fall back to `"displayName"` (should probably be organization name)

2022-12-17 14:28 UTC, ikusteu commented on packages/client/src/store/actions/bookingOperations.ts
> +  ({ icsFile, email, secretKey, displayName = "displayName", name = "name" }) =>
Same goes for `name`

2022-12-17 14:28 UTC, ikusteu commented on packages/client/src/__tests__/migrations.test.ts
> +          });
Can we just remove this test...out CI server is overworked anyway, the test is failing and is not really necessary

2022-12-17 14:28 UTC, ikusteu commented on packages/client/src/__testSetup__/node.ts
> +        SendCalendarFileTemplate,
I'm gonna go out on a limb and say this is the reason the tests below are failing. Just make it an object (like I've described) and it should be good to go.

2022-12-17 14:28 UTC, ikusteu commented on packages/shared/src/types/firestore.ts
> +   * Templates for reminder emails
Not only for reminders

2022-12-17 14:28 UTC, ikusteu commented on packages/shared/src/types/firestore.ts
> +    [name: string]: {
We can assume it will always be present

2022-12-17 14:28 UTC, ikusteu commented on packages/shared/src/utils/organization.ts
> +  const placeholders = template.match(/\{\{ (.*?) \}\}/g) || [""];
I would like the whitespace to be optional (so `{{name }}` would also work)

2022-12-18 16:04 UTC, fadwamahmoud commented on packages/client/src/features/modal/components/ExtendBookingDateDialog/utils.ts
> +          email: email || "",
it's optional all the way back in customer (which is what's passed to sendBookingsLink) so what do I make it fall back to?

2022-12-18 16:10 UTC, ikusteu commented on packages/client/src/features/modal/components/ExtendBookingDateDialog/utils.ts
> +          email: email || "",
Well...we can't send an email if one is not provided...

2022-12-18 16:11 UTC, ikusteu commented on packages/client/src/features/modal/components/ExtendBookingDateDialog/utils.ts
> +          email: email || "",
Besides, send bookings link button is disabled if there's no email present. Let's enforce better checks and assure that the email will, in fact be present in `sendEmail` function.

2022-12-18 16:37 UTC, ikusteu commented on packages/client/src/features/modal/components/ExtendBookingDateDialog/utils.ts
> +          email: email || "",
Ok...taking another look at it...let's just add `email!` non-null assertion and let the cloud function take care of it. It should throw a validation error if email is not present...

2022-12-28 13:41 UTC, merged